---
# tasks file for roles/opensuse_es

- name: install vsftpd
  zypper:
    name: vsftpd
    state: latest
    update_cache: yes

- name: stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: creating ftp user
  user:
    name: lmrada-tip1
    password: $5$TEnFuE6bHhoPbzJi$N2jfRydX98CVIyNw7Acn4xF9v66ZK0NP3.JY1KTcEc2
    comment: "ftp user"

- name: creating ftp group
  group:
    name: lmrada-tip1

- name: adding deny user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers lmrada-tip1"
  register: sshd_config

- name: restarting sshd service
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: creating ftp dir
  file:
    path: /home/lmrada-tip1/ftp
    state: directory
    owner: lmrada-tip1
    group: lmrada-tip1

- name: creating ftp dir file
  file:
    path: /home/lmrada-tip1/ftp/files
    state: directory
    owner: lmrada-tip1
    group: lmrada-tip1

- name: copying vsftpd
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: deleting line in vsftpd.conf
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: 'secure_chroot_dir=/var/run/vsftpd/empty'

- name: restarting vsftpd.conf
  service:
    name: vsftpd
    state: started
  when: vsftpd_config.changed
